### ISSUE TITLE
Documentation: describe how to change the security options 

### ISSUE THREAD

**Issue by pablomalo** [schmidhorst/synology-autorun#5]
During the installation, there is a step for setting up the security configuration, i.e. registering script hashes.

The dialog advises the user that if selecting option 2 (i.e. add to the registered scripts any script matching the predefined script name), the user should change that later to option 3 (i.e. only previously registered hashes are allowed to execute).

It is not clear to me how that option can be changed at a later stage.

Maybe this could be made explicit in the README ?

I appreciate the package !

**Comment by schmidhorst** [comment]
The available way to change settings is to re-run the installation.
The values, which you have entered during the previous installation will be the defaults then. And your registered hashes are preserved as long you don't select option 1.

At the bottom of the SETTINGS page there is a hint: 
You may run the installation again to change the settings or to delete the checksums!
